### ISSUE TITLE
Finalize and deploy the version 1.0.0

### ISSUE THREAD

**Issue by Carl-Hugo** [ForEvolve/ForEvolve-Framework#18]
## TODO
- [x] Complete all v1.0.0 tasks
    - [x] #32
    - [x] #33
- [x] Cleanup `ForEvolve.ApplicationInsights` 
    - [x] Move `ForEvolve.ApplicationInsights` to `ForEvolve.Azure\ApplicationInsights` in a new branch `feature/application-insights`. 
    - [x] Delete the code from `master`. 
    - [x] Create an issue about implementing something useful there (like a sub-session system, see other project).
- [x] Add a `TraitAttribute` to tests that use the Azure Storage Emulator
- [x] Validate that all packages target `netstandard2.0`
- [x] Create community files in the Toc repo
- [x] Create community files in all repos; reference the Toc repo files for `CODE_OF_CONDUCT` and `CONTRIBUTING`; create `ISSUE_TEMPLATE`s
    - [x] ForEvolve-Framework
    - [x] ForEvolve.AspNetCore.Localization
- [x] Cleanup project files
    - [x] ForEvolve-Framework
    - [x] ForEvolve.AspNetCore.Localization
- [x] Review the `ForEvolve.AspNetCore.UserIdFinder` directory
- [x] Review the `ForEvolve.AspNetCore.Middleware` directory
- [x] Review the `ForEvolve.AspNetCore.HttpRequestValueFinder` directory; atm, the implementation only look into request headers.
    - [x] Update `services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();` to 
`services.AddHttpContextAccessor()` in [ForEvolveAspNetCoreStartupExtensions.cs](https://github.com/ForEvolve/ForEvolve-Framework/blob/master/src/ForEvolve.AspNetCore/Microsoft.Extensions.DependencyInjection/ForEvolveAspNetCoreStartupExtensions.cs)
    - [x] Extract an `AddHttpRequestValueFinder()` extension method that encapsulate both adding `IHttpRequestValueFinder` elements and the `IHttpContextAccessor`; allowing to not load the `IHttpContextAccessor` if not used (for performance gain). Validate where `IHttpContextAccessor` is used in the project to se if it is possible.
- [x] Remove the `CodeCoverage`dependency ~~during release builds~~
- [x] Update readme and create one readme per project
    - [x] Include a PDF example. (clean and push `ForEvolvePdfNuGetExperiment` to a new `ForEvolve.Samples` repo)
    - [x] Update all `services.Add*` to `services.AddForEvolve*` when required.
    - [x] Update all `services.Configure*` to `services.ConfigureForEvolve*` when required.
    - [x] Review `ForEvolve.DynamicInternalServerError` and `ForEvolve.DynamicInternalServerError.Swagger` README
    - [x] Create/review markdown, pdf and xunit readme files.
- [x] Deploy v1 to NuGet (this project packages)
    - [x] Complete PR #28 
    - [x] Deploy an RC1 version
    - [x] Run some tests
    - [x] Fix bugs
    - [x] Deploy the v1.0.0 final version
